<?php
/**
 * @var Openstream_GeoIP_Block_System_Config_Synchronize $this
 */

/**
 * Returns you the ISO 3166-1 code of visitors country.
 */
?>

<script type="text/javascript">
//<![CDATA[
    var u = {};
    var geoipUrl = {
        'country': {
            status: '<?php echo $this->getAjaxStatusUpdateUrl("country") ?>',
            sync: '<?php echo $this->getAjaxSyncUrl("country") ?>'
        },
        'city': {
            status: '<?php echo $this->getAjaxStatusUpdateUrl("city") ?>',
            sync: '<?php echo $this->getAjaxSyncUrl("city") ?>'
        }
    }

    function enableSyncButton() {
        Form.Element.enable('synchronize_button');
        $('synchronize_button').removeClassName('disabled');
    }

    function disableSyncButton() {
        Form.Element.disable('synchronize_button');
        $('synchronize_button').addClassName('disabled');
    }

    function checkStatus(index) {
        u[index] = new Ajax.PeriodicalUpdater('', geoipUrl[index].status,
        {
            method:     'get',
            frequency:  1,
            loaderArea: false,

            onSuccess: (function(prefix)
            {
                return function(transport) {
                    try {
                        var percent = parseInt(transport.responseText);
                        if (percent == 100) {
                            u[prefix].stop();
                            $(prefix + '_sync_span').addClassName('no-display');
                            enableSyncButton();
                        } else {
                            $(prefix + '_sync_message_span').update(percent + '%');
                        }
                    } catch (e) { }
                }
            })(index)
        });
    }

    function synchronize()
    {
        disableSyncButton();
        for (var index in geoipUrl)
        {
            if (!geoipUrl.hasOwnProperty(index)) continue;
            var url = geoipUrl[index];

            $(index + '_sync_span_error').addClassName('no-display');
            $(index + '_sync_span').removeClassName('no-display');
            $(index + '_sync_message_span').update('0%');
            new Ajax.Request(url.sync, {
                loaderArea:     false,
                asynchronous:   true,

                onSuccess: (function(prefix)
                {
                    return function(transport) {
                        enableSyncButton();
                        var response = eval('(' + transport.responseText + ')');
                        if (response.status == 'success') {
                            $(prefix + '_sync_update_date').update(response.date);
                        } else {
                            $(prefix + '_sync_span').addClassName('no-display');
                            $(prefix + '_sync_span_error').removeClassName('no-display').update(response.message);
                        }
                        u[prefix].stop();
                    }
                })(index)
            });
            (function(a)
            {
                window.setTimeout(function()
                {
                    checkStatus(a)
                }, 1000);
            })(index);

            // window.setTimeout(function (a) { checkStatus(index); }, 1000);
        };
    }
//]]>
</script>

<?php echo $this->getButtonHtml() ?>